# Generated by Django 6.0.4 on 2026-05-04 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0003_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('no_response', 'No Response'), ('replied', 'Replied'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proposal_ai.proposal')),
            ],
        ),
    ]
