# Generated by Django 6.0.4 on 2026-05-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0005_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='experience_depth',
            field=models.TextField(blank=True, null=True),
        ),
    ]
