# Generated by Django 6.0.4 on 2026-05-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0006_remove_workexperience_years_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='main_skills',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='profile_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
