# Generated by Django 6.0.4 on 2026-05-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0007_remove_freelancerprofile_main_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('used', 'Used'), ('reply', 'Reply'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('no_response', 'No Response')], default='generated', max_length=50),
        ),
        migrations.AddField(
            model_name='proposal',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='used_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
