# Generated by Django 6.0.4 on 2026-05-21 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0008_proposal_status_proposal_used_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalUseConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('submitted_proposal_text', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proposal_ai.proposal')),
            ],
        ),
    ]
