# Generated by Django 6.0.4 on 2026-05-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0009_proposaluseconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='budget_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='client_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='confirmed_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='hourly_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='hourly_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='hours_per_week',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='interviewing_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='invites_sent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='project_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='proposal_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='raw_job_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
