# Generated by Django 6.0.4 on 2026-05-24 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0010_jobpost_budget_type_jobpost_client_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposaloutcome',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='proposaloutcome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposaloutcome',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposaloutcome',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
