# Generated by Django 6.0.4 on 2026-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0011_remove_proposaloutcome_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='content_type',
            field=models.CharField(choices=[('cover_letter', 'Cover Letter'), ('proposal_text', 'Proposal Text'), ('application_message', 'Application Message'), ('pitch', 'Pitch')], default='proposal_text', max_length=50),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('submitted', 'Submitted'), ('used', 'Used'), ('reply', 'Reply'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('no_response', 'No Response')], default='generated', max_length=50),
        ),
    ]
