# Generated by Django 6.0.4 on 2026-07-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0012_proposal_content_type_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='fixed_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
