# Generated by Django 6.0.4 on 2026-10-01 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0013_jobpost_fixed_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('profile_summary', 'Profile summary'), ('job_extraction', 'Job extraction'), ('proposal_generation', 'Proposal generation')], max_length=24)),
                ('nonce', models.UUIDField()),
                ('intent', models.CharField(choices=[('generate', 'Generate'), ('regenerate', 'Regenerate')], max_length=12)),
                ('submitted_fingerprint', models.CharField(max_length=64)),
                ('effective_fingerprint', models.CharField(max_length=64)),
                ('lifecycle', models.CharField(choices=[('reserved', 'Reserved'), ('in_flight', 'In flight'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('uncertain', 'Uncertain')], default='reserved', max_length=12)),
                ('quota_state', models.CharField(choices=[('reserved', 'Reserved'), ('consumed', 'Consumed'), ('released', 'Released')], default='reserved', max_length=8)),
                ('quota_units', models.PositiveSmallIntegerField(editable=False)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dispatch_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField()),
                ('failure_category', models.CharField(blank=True, choices=[('local_configuration', 'Local configuration'), ('configuration', 'Provider configuration rejection'), ('capacity', 'Provider capacity rejection'), ('invalid_request', 'Provider request rejection'), ('input_limit', 'Input validation'), ('timeout', 'Timeout'), ('connection', 'Connection'), ('temporary', 'Temporary failure'), ('invalid_response', 'Invalid response'), ('persistence', 'Persistence failure'), ('coordination', 'Coordination failure'), ('stale', 'Expired request'), ('unexpected', 'Unexpected failure')], max_length=24)),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal_ai.jobpost')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposal_ai.proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'admitted_at'], name='ai_request_user_admitted'), models.Index(fields=['user', 'operation', 'dispatch_started_at'], name='ai_request_user_burst'), models.Index(fields=['lifecycle', 'lease_expires_at'], name='ai_request_stale')],
                'constraints': [models.UniqueConstraint(fields=('user', 'nonce'), name='ai_request_user_nonce_unique'), models.UniqueConstraint(condition=models.Q(('lifecycle__in', ('reserved', 'in_flight'))), fields=('user',), name='ai_request_one_active_user'), models.CheckConstraint(condition=models.Q(models.Q(('operation', 'profile_summary'), ('quota_units', 1)), models.Q(('operation', 'job_extraction'), ('quota_units', 2)), models.Q(('operation', 'proposal_generation'), ('quota_units', 3)), _connector='OR'), name='ai_request_operation_units')],
            },
        ),
    ]
