# Generated by Django 6.0.4 on 2026-10-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0014_ai_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='api_style',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='cached_input_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='completion_token_cap',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='completion_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='finish_reason',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='input_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='provider',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='provider_latency_ms',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='reasoning_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='requested_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='response_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='response_text_characters',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='service_tier',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='airequest',
            name='total_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('local_configuration', 'Local configuration'), ('configuration', 'Provider configuration rejection'), ('authentication', 'Provider authentication rejection'), ('capacity', 'Provider capacity rejection'), ('invalid_request', 'Provider request rejection'), ('input_limit', 'Input validation'), ('timeout', 'Timeout'), ('connection', 'Connection'), ('temporary', 'Temporary failure'), ('invalid_response', 'Invalid response'), ('incomplete_response', 'Incomplete response'), ('oversized_response', 'Oversized response'), ('persistence', 'Persistence failure'), ('coordination', 'Coordination failure'), ('stale', 'Expired request'), ('unexpected', 'Unexpected failure')], max_length=24),
        ),
    ]
