# Generated by Django 6.0.4 on 2026-10-02 15:03

import django.db.models.deletion
from datetime import timedelta, timezone
from django.db import migrations, models


def bootstrap_periods(apps, schema_editor):
    """Copy only known product-credit evidence; no invented limits/AI usage.

    Run as an atomic release migration with old AI-writing workers stopped.
    Historical models and the migration's connection keep this reproducible.
    """
    requests = apps.get_model('proposal_ai', 'AIRequest').objects.using(schema_editor.connection.alias)
    periods = apps.get_model('proposal_ai', 'AIQuotaPeriod').objects.using(schema_editor.connection.alias)
    for row in requests.order_by('pk').iterator(chunk_size=1000):
        day = row.admitted_at.astimezone(timezone.utc).date()
        week = day - timedelta(days=day.weekday())
        daily, _ = periods.get_or_create(kind='daily', period_start=day)
        weekly, _ = periods.get_or_create(kind='weekly', period_start=week)
        requests.filter(pk=row.pk).update(global_day_period_id=daily.pk, global_week_period_id=weekly.pk)
        if row.quota_state == 'released':
            continue
        if row.quota_state not in ('reserved', 'consumed'):
            raise RuntimeError('Historical AIRequest accounting is invalid; review the ledger before deployment.')
        field = 'reserved_credits' if row.quota_state == 'reserved' else 'consumed_credits'
        periods.filter(pk__in=(daily.pk, weekly.pk)).update(**{field: models.F(field) + row.quota_units})


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_ai', '0015_ai_request_telemetry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('ai_disabled', 'AI disabled before provider execution'), ('local_configuration', 'Local configuration'), ('configuration', 'Provider configuration rejection'), ('authentication', 'Provider authentication rejection'), ('capacity', 'Provider capacity rejection'), ('invalid_request', 'Provider request rejection'), ('input_limit', 'Input validation'), ('timeout', 'Timeout'), ('connection', 'Connection'), ('temporary', 'Temporary failure'), ('invalid_response', 'Invalid response'), ('incomplete_response', 'Incomplete response'), ('oversized_response', 'Oversized response'), ('persistence', 'Persistence failure'), ('coordination', 'Coordination failure'), ('stale', 'Expired request'), ('unexpected', 'Unexpected failure')], max_length=24),
        ),
        migrations.CreateModel(
            name='AIQuotaPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], editable=False, max_length=6)),
                ('period_start', models.DateField(editable=False)),
                ('credit_limit', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('reserved_credits', models.BigIntegerField(default=0, editable=False)),
                ('consumed_credits', models.BigIntegerField(default=0, editable=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'period_start'), name='ai_quota_period_unique'), models.CheckConstraint(condition=models.Q(('kind__in', ('daily', 'weekly'))), name='ai_quota_period_kind'), models.CheckConstraint(condition=models.Q(('reserved_credits__gte', 0)), name='ai_quota_reserved_nonnegative'), models.CheckConstraint(condition=models.Q(('consumed_credits__gte', 0)), name='ai_quota_consumed_nonnegative'), models.CheckConstraint(condition=models.Q(('credit_limit__isnull', True), ('credit_limit__gte', 0), _connector='OR'), name='ai_quota_limit_nonnegative')],
            },
        ),
        migrations.AddField(
            model_name='airequest',
            name='global_day_period',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_requests', to='proposal_ai.aiquotaperiod'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='global_week_period',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_requests', to='proposal_ai.aiquotaperiod'),
        ),
        migrations.RunPython(bootstrap_periods, migrations.RunPython.noop),
    ]
