from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("proposal_ai", "0016_ai_global_exposure")]

    operations = [
        migrations.CreateModel(
            name="ResearchDataset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_name", models.CharField(max_length=255)),
                ("source_sha256", models.CharField(max_length=64, unique=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("case_count", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={"ordering": ("-imported_at",)},
        ),
        migrations.CreateModel(
            name="ResearchCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("case_key", models.CharField(max_length=64)),
                ("participant_key", models.CharField(blank=True, max_length=64)),
                ("round_label", models.CharField(blank=True, max_length=100)),
                ("case_type", models.CharField(blank=True, max_length=50)),
                ("outcome", models.CharField(blank=True, max_length=100)),
                ("application_route", models.CharField(blank=True, max_length=100)),
                ("client_relationship", models.CharField(blank=True, max_length=100)),
                ("domain_niche", models.TextField(blank=True)),
                ("job_title", models.TextField(blank=True)),
                ("budget_type", models.CharField(blank=True, max_length=100)),
                ("budget_low", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("budget_high", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("submitted_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("final_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("competition_timing", models.TextField(blank=True)),
                ("record_status", models.CharField(blank=True, max_length=100)),
                ("job_core_problem", models.TextField(blank=True)),
                ("primary_stack_domain", models.TextField(blank=True)),
                ("required_skills", models.TextField(blank=True)),
                ("explicit_instructions", models.TextField(blank=True)),
                ("scope_complexity", models.CharField(blank=True, max_length=100)),
                ("risk_signals", models.TextField(blank=True)),
                ("observable_fit_signals", models.TextField(blank=True)),
                ("opening_approach", models.TextField(blank=True)),
                ("experience_evidence", models.TextField(blank=True)),
                ("direct_job_match_evidence", models.TextField(blank=True)),
                ("solution_approach", models.TextField(blank=True)),
                ("tools_stack", models.TextField(blank=True)),
                ("instruction_coverage", models.TextField(blank=True)),
                ("strong_features", models.TextField(blank=True)),
                ("observable_gaps", models.TextField(blank=True)),
                ("outcome_confounds", models.TextField(blank=True)),
                ("source_fidelity", models.CharField(blank=True, max_length=150)),
                ("dataset", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="cases", to="proposal_ai.researchdataset")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("dataset", "case_key"), name="research_case_dataset_key_unique")],
                "indexes": [models.Index(fields=("dataset", "outcome"), name="research_case_outcome"), models.Index(fields=("dataset", "case_key"), name="research_case_key")],
            },
        ),
        migrations.CreateModel(
            name="ResearchRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requirement", models.TextField()),
                ("importance", models.CharField(blank=True, max_length=100)),
                ("proposal_evidence", models.TextField(blank=True)),
                ("coverage", models.CharField(blank=True, max_length=50)),
                ("interpretation_note", models.TextField(blank=True)),
                ("research_case", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="requirements", to="proposal_ai.researchcase")),
            ],
            options={"indexes": [models.Index(fields=("research_case", "coverage"), name="research_req_coverage")]},
        ),
        migrations.CreateModel(
            name="ResearchNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("case_key", models.CharField(blank=True, max_length=64)),
                ("note_type", models.CharField(blank=True, max_length=50)),
                ("observation", models.TextField()),
                ("why_it_matters", models.TextField(blank=True)),
                ("confidence", models.CharField(blank=True, max_length=50)),
                ("do_not_overclaim", models.TextField(blank=True)),
                ("dataset", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="notes", to="proposal_ai.researchdataset")),
            ],
            options={"indexes": [models.Index(fields=("dataset", "case_key"), name="research_note_case") ]},
        ),
    ]
